#Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'carrot_market_clona_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.5'
  pod 'YPImagePicker'  
  pod 'BSImagePicker', '~> 3.1' 
 # Pods for carrot_market_clona_ios

end
